version: "3.9"
services:
  backend:
    build: ./backend
    container_name: iis-analyzer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data/uploads:/app/data/uploads
      - ./backend/data/analyses:/app/data/analyses

  frontend:
    build: ./frontend
    container_name: iis-analyzer-frontend
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "30000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
