version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: dump-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: dump-frontend
    ports:
      - "30000:30000"
    depends_on:
      - backend
