version: '3.7'

x-volumes: &volumes
  postgres_data:
  media:
  static:
  rabbitmq_data:
  redis_data:

x-default-back-environment: &default-back-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_NAME: ${POSTGRES_DB:-taiga}
  RABBITMQ_USER: ${RABBITMQ_USER}
  RABBITMQ_PASS: ${RABBITMQ_PASS}
  RABBITMQ_VHOST: ${RABBITMQ_VHOST}
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
  EMAIL_BACKEND: ${EMAIL_BACKEND}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PORT: ${EMAIL_PORT}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  EMAIL_USE_TLS: ${EMAIL_USE_TLS}
  EMAIL_USE_SSL: ${EMAIL_USE_SSL}
  EMAIL_DEFAULT_FROM: ${EMAIL_DEFAULT_FROM}
  SECRET_KEY: ${SECRET_KEY}
  TAIGA_SITES_SCHEME: ${TAIGA_SCHEME}
  TAIGA_SITES_DOMAIN: ${TAIGA_DOMAIN}
  FORCE_SCRIPT_NAME: ${SUBPATH}
  ENABLE_TELEMETRY: ${ENABLE_TELEMETRY}

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-taiga}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: [*default-back-environment]
    volumes:
      - static:/taiga-back/static
      - media:/taiga-back/media
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped

  taiga-async:
    image: taigaio/taiga-back:latest
    command: celery -A taiga.celery worker -l info
    environment: [*default-back-environment]
    volumes:
      - static:/taiga-back/static
      - media:/taiga-back/media
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/${RABBITMQ_VHOST}"
      SECRET: ${SECRET_KEY}
      WEB_SOCKET_SERVER_PORT: 8888
    depends_on:
      - rabbitmq
    restart: unless-stopped

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      TAIGA_SUBPATH: ${SUBPATH}
      MAX_AGE: ${ATTACHMENTS_MAX_AGE}
    volumes:
      - media:/taiga-protected/media
    depends_on:
      - taiga-back
    restart: unless-stopped

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}${SUBPATH}"
      TAIGA_API: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}${SUBPATH}/api/v1/"
      TAIGA_EVENTS: "${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}${SUBPATH}/events"
      PUBLIC_REGISTER_ENABLED: "false"
    ports:
      - "9000:80"
    depends_on:
      - taiga-back
      - taiga-events
    restart: unless-stopped
