version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dump-backend
    ports:
      - "5000:5000"
    networks:
      - dumpnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dump-frontend
    ports:
      - "30000:3000"
    depends_on:
      - backend
    networks:
      - dumpnet

networks:
  dumpnet:
    driver: bridge
