version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga_pass_segura
      - POSTGRES_DB=taiga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga_pass_segura
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=taiga
      - SECRET_KEY=taiga-secret-key-aqui
      - TAIGA_SITES_SCHEME=http
      - TAIGA_SITES_DOMAIN=localhost:9000
      - EMAIL_BACKEND=console
    volumes:
      - static:/taiga-back/static
      - media:/taiga-back/media
    depends_on:
      - postgres
    restart: unless-stopped

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      - TAIGA_URL=http://localhost:9000
      - TAIGA_API=http://localhost:9000/api/v1/
      - PUBLIC_REGISTER_ENABLED=false
    ports:
      - "9000:80"
    depends_on:
      - taiga-back
    restart: unless-stopped

volumes:
  postgres_data:
  media:
  static:
