version: "3.9"

services:

  exporter:
    build: ./exporter
    container_name: pritunl_exporter
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
      - influxdb

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    volumes:
      - influx_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.0.0
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

volumes:
  mongo_data:
  influx_data:
