version: '3.8'

services:
  backend:
  image: python:3.11-slim
  container_name: stack-translator_backend
  ports:
    - "8000:8000"
  volumes:
    - ./backend/app:/app
  working_dir: /app
  command: python main.py
  restart: unless-stopped


  frontend:
    build: ./frontend
    container_name: stack-translator_frontend
    ports:
      - "30000:3000"
    depends_on:
      - backend
    restart: unless-stopped
