version: '3.8'

services:
  backend:
    image: ghcr.io/library/python:3.11-slim
    container_name: stack-translator_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    working_dir: /app
    command: python main.py  # ajuste para o comando que inicia seu backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stack-translator_frontend
    ports:
      - "30000:3000"
    depends_on:
      - backend
    restart: unless-stopped
