version: "3.9"

services:
  analyzer:
    build: .
    container_name: dump_analyzer
    ports:
      - "30000:5000"
    volumes:
      - ./app/uploads:/tmp/uploads
    environment:
      - FLASK_ENV=development
