version: '3.8'

services:
  iis-log-analyzer:
    build: .
    container_name: iis-log-analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/app/static
    restart: unless-stopped
