version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stack-translator_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stack-translator_frontend
    ports:
      - "30000:3000"
    depends_on:
      - backend
    restart: unless-stopped
