version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: powerdns-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change in production!
      MYSQL_DATABASE: powerdns
      MYSQL_USER: pdns
      MYSQL_PASSWORD: pdnspass  # Change in production!
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Updated init script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 20s
      retries: 10

  pdns:
    image: powerdns/pdns-auth-49:latest  # Use a newer version
    container_name: powerdns
    restart: unless-stopped
    command: >
      pdns_server
      --api=yes
      --api-key=pdns-api-key
      --webserver=yes
      --webserver-address=0.0.0.0
      --webserver-port=8081
      --launch=gmysql
      --gmysql-host=db
      --gmysql-user=pdns
      --gmysql-password=pdnspass
      --gmysql-dbname=powerdns
    ports:
      - "15053:53/tcp"
      - "15053:53/udp"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - powerdns-net

  powerdns-admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns-admin
    restart: unless-stopped
    ports:
      - "9191:80"
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://pda:pdaadmin@db/powerdns
      SECRET_KEY: super-secret-key-change-me!  # Change in production!
      PDNS_API_URL: http://pdns:8081
      PDNS_API_KEY: pdns-api-key
      GUNICORN_WORKERS: 3
    depends_on:
      db:
        condition: service_healthy
      pdns:
        condition: service_started
    volumes:
      - admin_data:/data
    networks:
      - powerdns-net

volumes:
  db_data:
  admin_data:

networks:
  powerdns-net:
    name: powerdns-net
